#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
IMAGE="$2"
HOSTNAME=$(hostname -f)

if [[ -f "$DOKKU_ROOT/$APP/DISCORD_URL" || -f "$DOKKU_ROOT/DISCORD_URL" ]]; then
  echo "-----> Notifying Slack ..."
  URL=$(dokku url $APP)
  DISCORD_URL=$(cat "$DOKKU_ROOT/$APP/DISCORD_URL" 2> /dev/null || cat "$DOKKU_ROOT/DISCORD_URL" 2> /dev/null)
  DISCORD_JSON="{ \
    \"attachments\": [{ \
      \"text\": \"Deployed $APP to $HOSTNAME via $URL\", \
      \"fallback\": \"Deployed $APP to $HOSTNAME via $URL\", \
      \"color\": \"good\", \
      \"mrkdwn_in\": [\"text\"] \
    }] \
  }"
  DISCORD_RESULT=$(curl -s -d "payload=$DISCORD_JSON" "${DISCORD_URL}" -w "%{http_code}")
  echo "       ${DISCORD_RESULT}"
fi
